#Enable pebbles?
enablePebbles = true
#When right clicking to get pebbles, should it emit sound?
emitPebbleSound = true
#Block to pebble mappings
blockPebbleMappings = ["minecraft:dirt;havenpebbles:andesite_pebble:15,havenpebbles:calcite_pebble:10,havenpebbles:deepslate_pebble:10,havenpebbles:diorite_pebble:10,havenpebbles:dripstone_pebble:10,havenpebbles:granite_pebble:10,havenpebbles:tuff_pebble:10,havenpebbles:stone_pebble:40", "minecraft:grass_block;havenpebbles:andesite_pebble:15,havenpebbles:calcite_pebble:10,havenpebbles:deepslate_pebble:10,havenpebbles:diorite_pebble:10,havenpebbles:dripstone_pebble:10,havenpebbles:granite_pebble:10,havenpebbles:tuff_pebble:10,havenpebbles:stone_pebble:40", "minecraft:netherrack;havenpebbles:netherrack_pebble:90,havenpebbles:basalt_pebble:10,havenpebbles:blackstone_pebble:5"]
