#Enable pebbles?
enablePebbles = true
#When right clicking to get pebbles, should it emit sound?
emitPebbleSound = true
#Block to pebble mappings
blockPebbleMappings = ["minecraft:dirt;havenpebbles:stone_pebble:35,havenpebbles:tuff_pebble:30,havenpebbles:andesite_pebble:15,havenpebbles:dripstone_pebble:10,havenpebbles:calcite_pebble:5,havenpebbles:diorite_pebble:5,havenpebbles:granite_pebble:5", "minecraft:grass_block;havenpebbles:stone_pebble:35,havenpebbles:tuff_pebble:30,havenpebbles:andesite_pebble:20,havenpebbles:dripstone_pebble:10,havenpebbles:calcite_pebble:5,havenpebbles:diorite_pebble:5,havenpebbles:granite_pebble:5", "minecraft:netherrack;havenpebbles:netherrack_pebble:90,havenpebbles:basalt_pebble:10,havenpebbles:blackstone_pebble:5"]
